In [1]:
# Import necessary libraries
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import math

# Import scikit-learn modules
from sklearn import datasets
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_regression
from sklearn.model_selection import GridSearchCV 

In [2]:
Air_Quality=pd.read_excel("C:\Sravan ML\ML_git\Random Forest\AirQualityUCI.xlsx")
Air_Quality

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)   C6H6(GT)  \
0    2004-03-10  18:00:00     2.6      1360.00       150  11.881723   
1    2004-03-10  19:00:00     2.0      1292.25       112   9.397165   
2    2004-03-10  20:00:00     2.2      1402.00        88   8.997817   
3    2004-03-10  21:00:00     2.2      1375.50        80   9.228796   
4    2004-03-10  22:00:00     1.6      1272.25        51   6.518224   
...         ...       ...     ...          ...       ...        ...   
9352 2005-04-04  10:00:00     3.1      1314.25      -200  13.529605   
9353 2005-04-04  11:00:00     2.4      1162.50      -200  11.355157   
9354 2005-04-04  12:00:00     2.4      1142.00      -200  12.374538   
9355 2005-04-04  13:00:00     2.1      1002.50      -200   9.547187   
9356 2005-04-04  14:00:00     2.2      1070.75      -200  11.932060   

      PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  \
0           1045.50    166.0       1056.25    113.0       1692.00   
1            954.75    103.0       1173.75     92.0       1558.75   
2            939.25    131.0       1140.00    114.0       1554.50   
3            948.25    172.0       1092.00    122.0       1583.75   
4            835.50    131.0       1205.00    116.0       1490.00   
...             ...      ...           ...      ...           ...   
9352        1101.25    471.7        538.50    189.8       1374.25   
9353        1027.00    353.3        603.75    179.2       1263.50   
9354        1062.50    293.0        603.25    174.7       1240.75   
9355         960.50    234.5        701.50    155.7       1041.00   
9356        1047.25    265.2        654.00    167.7       1128.50   

      PT08.S5(O3)       T         RH        AH  
0         1267.50  13.600  48.875001  0.757754  
1          972.25  13.300  47.700000  0.725487  
2         1074.00  11.900  53.975000  0.750239  
3         1203.25  11.000  60.000000  0.786713  
4         1110.00  11.150  59.575001  0.788794  
...           ...     ...        ...       ...  
9352      1728.50  21.850  29.250000  0.756824  
9353      1269.00  24.325  23.725000  0.711864  
9354      1092.00  26.900  18.350000  0.640649  
9355       769.75  28.325  13.550000  0.513866  
9356       816.00  28.500  13.125000  0.502804  

[9357 rows x 15 columns]

In [3]:
Air_Quality['Date']=pd.to_datetime(Air_Quality['Date'])
Air_Quality.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9357 entries, 0 to 9356
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   Date           9357 non-null   datetime64[ns]
 1   Time           9357 non-null   object        
 2   CO(GT)         9357 non-null   float64       
 3   PT08.S1(CO)    9357 non-null   float64       
 4   NMHC(GT)       9357 non-null   int64         
 5   C6H6(GT)       9357 non-null   float64       
 6   PT08.S2(NMHC)  9357 non-null   float64       
 7   NOx(GT)        9357 non-null   float64       
 8   PT08.S3(NOx)   9357 non-null   float64       
 9   NO2(GT)        9357 non-null   float64       
 10  PT08.S4(NO2)   9357 non-null   float64       
 11  PT08.S5(O3)    9357 non-null   float64       
 12  T              9357 non-null   float64       
 13  RH             9357 non-null   float64       
 14  AH             9357 non-null   float64       
dtypes: datetime64[ns](1),

In [4]:
Air_Quality.isna().sum()

Date             0
Time             0
CO(GT)           0
PT08.S1(CO)      0
NMHC(GT)         0
C6H6(GT)         0
PT08.S2(NMHC)    0
NOx(GT)          0
PT08.S3(NOx)     0
NO2(GT)          0
PT08.S4(NO2)     0
PT08.S5(O3)      0
T                0
RH               0
AH               0
dtype: int64

In [5]:
x = Air_Quality.drop(['Date', 'Time', 'CO(GT)'], axis=1) 
y = Air_Quality['CO(GT)']

In [6]:

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=5)

In [7]:

# Initialize the RandomForestRegressor
reg = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model using the training sets
reg.fit(x_train, y_train)


RandomForestRegressor(random_state=42)

In [8]:
y_pred = reg.predict(x_test)
y_pred.flatten()

array([   1.897     ,   -9.452     ,  -91.31955556, ..., -200.        ,
       -179.919     ,  -23.399     ])

In [9]:
from sklearn.metrics import mean_absolute_error

# Ensure y_train and y_pred have the same number of samples
y_train = y_train[:len(y_pred)]

# Calculate the mean absolute error
mae = mean_absolute_error(y_train, y_pred)
print("Mean Absolute Error:", mae)

Mean Absolute Error: 60.99154947895677


In [10]:
# R2
r2 = r2_score(y_test, y_pred)
r2   

0.6032521998881553

In [11]:
from sklearn.model_selection import train_test_split

# Assuming you have your data ready
# x_train and y_train should represent corresponding features and target values

# Check the number of samples in x_train and y_train
if len(x_train) != len(y_train):
    # Print the lengths of x_train and y_train for debugging purposes
    print("Length of x_train:", len(x_train))
    print("Length of y_train:", len(y_train))
    
    # Check if the lengths can be aligned by selecting common indices
    common_indices = x_train.index.intersection(y_train.index)
    
    # Use common indices to align x_train and y_train
    x_train = x_train.loc[common_indices]
    y_train = y_train.loc[common_indices]
    
    print("After alignment:")
    print("Length of x_train:", len(x_train))
    print("Length of y_train:", len(y_train))

# Now you can proceed with your data preprocessing and model training


Length of x_train: 7485
Length of y_train: 1872
After alignment:
Length of x_train: 1872
Length of y_train: 1872


In [12]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

# Assuming you have defined your parameters and initialized the GridSearchCV
parameters = {
    'n_estimators': [100, 115, 120],
    'max_depth': [9, 10, 11, 12],
    'max_features': [3, 4, 5, 6],
    'max_leaf_nodes': [9, 10, 11, 120]
}

# Ensure that x_train and y_train have the same number of samples
if len(x_train) != len(y_train):
    # You may need to adjust your data splitting process to ensure consistency
    print("Number of samples in x_train and y_train are different. Please check your data splitting process.")
else:
    # Initialize the RandomForestRegressor
    reg1 = RandomForestRegressor()
    
    # Initialize GridSearchCV with the regressor and parameter grid
    grid_search = GridSearchCV(estimator=reg1, param_grid=parameters)
    
    


In [13]:
# Fit the GridSearchCV to your training data
grid_search.fit(x_train, y_train)

GridSearchCV(estimator=RandomForestRegressor(),
             param_grid={'max_depth': [9, 10, 11, 12],
                         'max_features': [3, 4, 5, 6],
                         'max_leaf_nodes': [9, 10, 11, 120],
                         'n_estimators': [100, 115, 120]})

In [14]:
y_pred_train = grid_search.predict(x_train)
y_pred_train.flatten()

array([ -11.0517059 ,    3.19682406,    0.41827435, ...,    5.10149906,
        -12.17372753, -183.09286623])

In [15]:
y_pred_test = grid_search.predict(x_test)
y_pred_test.flatten()

array([  -0.35063701,  -20.40682387, -115.65815437, ..., -180.16627015,
       -145.23014917,  -50.6698874 ])

In [16]:
best_estimator = grid_search.best_estimator_

In [17]:
mae = mean_absolute_error(y_train, y_pred_train)
print("Mean Absolute Error:", mae)

Mean Absolute Error: 16.33304787547277


In [18]:
# R2
r2 = r2_score(y_test, y_pred_test)
r2

0.5537865405984694

In [19]:
grid_search.best_index_    

9